#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $0${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre

parse_cmd_options() {
   trap "error_handler_general" ERR INT TERM

   while :
   do
       case $1 in
           -h | --help | -\?)
               script_help
               exit 0
               ;;
           -tg | --tor-gateway | --torgateway)
               export WHONIX_BUILD_GATEWAY="1"
               shift
               ;;
           -tw | --tor-workstation | --torworkstation)
               export WHONIX_BUILD_WORKSTATION="1"
               shift
               ;;
           --qcow2)
               export WHONIX_BUILD_QCOW2="true"
               shift
               ;;
           --nocompressqcow | --no-compress-qcow)
               export WHONIX_BUILD_NO_COMPRESS_QCOW="true"
               shift
               ;;
           --)
               shift
               break
               ;;
           -*)
               true "${cyan}INFO: Option $1 ignored in this script. This is not necessarily a problem.${reset}"
               ;;
           *)
               break
               ;;
       esac
   done

   if [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
      true
   else
      true "${green}Skipping $0, because parameter --qcow2 is not in use.${reset}"
      exit 0
   fi

   source variables
}

convert_img-to_qcow2() {
   trap "error_handler_general" ERR INT TERM

   if [ ! "$whonix_build_script_create_qcow2" = "1" ]; then
      true "INFO: Skipping $0, because whonix_build_script_create_qcow2 is not set to 1."
      return 0
   fi

   mkdir --parents "$WHONIX_BINARY/"
   chown --recursive "$user_name:$user_name" "$WHONIX_BINARY/"

   ## Debugging.
   sudo -u "$user_name" \
      qemu-img \
         info \
            "$WHONIX_BINARY/$VMNAME.img"

   sudo -u "$user_name" \
      qemu-img \
         convert \
            -p \
            -O qcow2 \
            -o cluster_size=2M \
            -o preallocation=metadata \
            "$WHONIX_BINARY/$VMNAME.img" \
            "$WHONIX_BINARY/$VMNAME-$whonix_build_whonix_version_new.qcow2"

   ## Debugging.
   sudo -u "$user_name" \
      qemu-img \
         info \
            "$WHONIX_BINARY/$VMNAME-$whonix_build_whonix_version_new.qcow2"
}

true "${bold}${under}INFO: Currently running script: $0 ${1+"$@"}${reset}"
parse_cmd_options ${1+"$@"}
convert_img-to_qcow2
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}${under}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
