#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $0${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre

parse_cmd_options() {
   trap "error_handler_general" ERR INT TERM

   while :
   do
       case $1 in
           -h | --help | -\?)
               script_help
               exit 0
               ;;
           -tg | --tor-gateway | --torgateway)
               export WHONIX_BUILD_GATEWAY="1"
               shift
               ;;
           -tw | --tor-workstation | --torworkstation)
               export WHONIX_BUILD_WORKSTATION="1"
               shift
               ;;
           -bm | --baremetal | --bare-metal)
               export BARE_METAL="1"
               shift
               ;;
           --vbox | --virtualbox | --virtual-box)
               export WHONIX_BUILD_VIRTUALBOX="true"
               shift
               ;;
           --qcow2)
               export WHONIX_BUILD_QCOW2="true"
               shift
               ;;
           --)
               shift
               break
               ;;
           -*)
               true "${cyan}INFO: Option $1 ignored in this script. This is not necessarily a problem.${reset}"
               ;;
           *)
               break
               ;;
       esac
   done

   if [ "$BARE_METAL" = "1" ]; then
      true
   elif [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      true
   elif [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
      true
   else
      error "${red}${bold}You must choose --bare-metal, --virtualbox or --qcow2.${reset}"
   fi

   source variables
}

create-report() {
   trap "error_handler_general" ERR INT TERM

   ## If whonix_build is run with --fast2 switch.
   if [ "$WHONIX_BUILD_FAST2" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast2 switch, skipping $0. ${reset}"
      exit 0
   fi

   local report_file
   report_file="$WHONIX_BINARY/$VMNAME-$whonix_build_whonix_version_new.report"

   local report_tempfolder
   report_tempfolder="$WHONIX_BINARY/$VMNAME-${whonix_build_whonix_version_new}_report_tempfolder"

   local topcomment
   topcomment="\
INFO: This is an auto-generated file.
See https://www.whonix.org/wiki/Verifiable_Builds
and https://www.whonix.org/wiki/Trust
to learn what this is about.
whonix_build_current_git_head: $whonix_build_current_git_head
whonix_build_new_changelog_version: $whonix_build_new_changelog_version
whonix_build_closest_git_tag: $whonix_build_closest_git_tag
BARE_METAL: $BARE_METAL"

   local endcomment
   endcomment="INFO: End."

   local errorcomment
   errorcomment="ERROR: Unfinished report! Error detected!"

   if [ "$whonix_build_script_minimal_report" = "1" ]; then
      true "${cyan}INFO: Only creating minimal report file because whonix_build_script_skip_report is 1.${reset}"
      rm --force "$report_file"
      echo "$topcomment" >> "$report_file"
      echo "Only creating minimal report file because whonix_build_script_skip_report is 1." >> "$report_file"
      echo "$endcomment" >> "$report_file"
      return 0
   fi

   if [ "$BARE_METAL" = "1" ]; then
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER/analyze_image" \
         --bare-metal \
         --report "$report_file" \
         --tempfolder "$report_tempfolder" \
         --topcomment "$topcomment" \
         --endcomment "$endcomment" \
         --errorcomment "$errorcomment"
   else
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER/analyze_image" \
         --ova "$WHONIX_BINARY/$VMNAME-$whonix_build_whonix_version_new.ova" \
         --report "$report_file" \
         --tempfolder "$report_tempfolder" \
         --topcomment "$topcomment" \
         --endcomment "$endcomment" \
         --errorcomment "$errorcomment"
   fi
}

true "${bold}${under}INFO: Currently running script: $0 ${1+"$@"}${reset}"
parse_cmd_options ${1+"$@"}
create-report
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}${under}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
