#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

script_help() {
echo "
## creates separate build folder
## "$HOMEVAR"/whonix_binary
##
## FLAGS:
## --build
## Build Whonix.
##
## --clean
## Deletes .img, .ova and VirtualBox VM's.
##
## --virtualbox
## Use this to build VirtualBox .ovas.
##
## --qcow2
## Use this to build qcow2 images.
##
## --bare-metal
## Use this for Whonix with physical isolation.
##
## --torgateway
## Builds Whonix-Gateway.
##
## --torworkstation
## Builds Whonix-Workstation.
##
## --all (not yet implemented)
## Build both machines.
"
}



whonix_build_cmdoptions() {
   trap "error_handler_general" ERR INT TERM

   ## Thanks to:
   ## http://mywiki.wooledge.org/BashFAQ/035

   if [ "$*" = "" ]; then
      error_out "${red}${bold}no option chosen. Use --help.${reset}"
   fi

   while :
   do
       case $1 in
           -h | --help | -\?)
               script_help
               exit 0
               ;;
           -tg | --tor-gateway | --torgateway)
               export WHONIX_BUILD_GATEWAY="1"
               shift
               ;;
           -tw | --tor-workstation | --torworkstation)
               export WHONIX_BUILD_WORKSTATION="1"
               shift
               ;;
           -bm | --baremetal | --bare-metal)
               export BARE_METAL="1"
               shift
               ;;
           --vbox | --virtualbox | --virtual-box)
               export WHONIX_BUILD_VIRTUALBOX="true"
               shift
               ;;
           --qcow2)
               export WHONIX_BUILD_QCOW2="true"
               shift
               ;;
           --nocompressqcow | --no-compress-qcow)
               export WHONIX_BUILD_NO_COMPRESS_QCOW="true"
               shift
               ;;
           -f1 | --fast1)
               export WHONIX_BUILD_FAST1="1"
               shift
               ;;
           -f2 | --fast2)
               export WHONIX_BUILD_FAST1="1"
               export WHONIX_BUILD_FAST2="1"
               shift
               ;;
           -c  | --clean)
               export WHONIX_BUILD_CLEAN="1"
               shift
               ;;
           -b  | --build)
               export WHONIX_BUILD_BUILD="1"
               shift
               ;;
           -i  | --internalrun)
               export WHONIX_BUILD_INTERNALRUN="1"
               shift
               ;;
           --)
               shift
               break
               ;;
           -*)
               error_out "${red}${bold}unknown option: $1${reset}"
               ;;
           *)
               break
               ;;
       esac
   done

   ## If there are input files (for example) that follow the options, they
   ## will remain in the "$@" positional parameters.

   if [ "$WHONIX_BUILD_ALL" = "1" ]; then
      error_out="${red}${bold}--all not yet implemented. (Help welcome!)${reset}"
   fi

   if [ ! "$WHONIX_BUILD_INTERNALRUN" = "1" ]; then
      if [ ! "$WHONIX_BUILD_MAIN_SCRIPT_STARTED" = "1" ]; then
         if [ "$WHONIX_BUILD_BUILD" = "1" ] && [ "$WHONIX_BUILD_CLEAN" = "1" ]; then
            error_out "${red}${bold}You must either use --build or --clean.${reset}"
         fi
      fi
   fi

   if [ "$WHONIX_BUILD_ALL" = "1" ] && [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      error_out "${red}${bold}You can not combine --all with --torgateway. You must either use --all or --torgateway.${reset}"
   fi

   if [ "$WHONIX_BUILD_ALL" = "1" ] && [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      error_out "${red}${bold}You can not combine --all with --torworkstation. You must either use --all or --torworkstation.${reset}"
   fi

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ] && [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      error_out "${red}${bold}You can not combine --torgateway with --torworkstation. Use --all if that is what you want.${reset}"
   fi

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ] || [ "$WHONIX_BUILD_WORKSTATION" = "1" ] || [ "$WHONIX_BUILD_ALL" = "1" ]; then
      true
   else
      error_out "${red}${bold}You must add --torgateway or --torworkstation or --all.${reset}"
   fi

   if [ "$BARE_METAL" = "1" ]; then
      true
   elif [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      true
   elif [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
      true
   else
      error_out "${red}${bold}You must choose --bare-metal, --virtualbox or --qcow2.${reset}"
   fi



}

whonix_build_cmdoptions ${1+"$@"}
