#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler_unchroot-img() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$MYDIR"/pre

parse_cmd_options() {
   trap "error_handler_general" ERR INT TERM

   while :
   do
       case $1 in
           -h | --help | -\?)
               script_help
               exit 0
               ;;
           -tg | --tor-gateway | --torgateway)
               export WHONIX_BUILD_GATEWAY="1"
               shift
               ;;
           -tw | --tor-workstation | --torworkstation)
               export WHONIX_BUILD_WORKSTATION="1"
               shift
               ;;
           -bm | --baremetal | --bare-metal)
               export BARE_METAL="1"
               shift
               ;;
           --vbox | --virtualbox | --virtual-box)
               export WHONIX_BUILD_VIRTUALBOX="true"
               shift
               ;;
           --qcow2)
               export WHONIX_BUILD_QCOW2="true"
               shift
               ;;
           --)
               shift
               break
               ;;
           -*)
               true "${cyan}INFO: Option $1 ignored in this script. This is not necessarily a problem.${reset}"
               ;;
           *)
               break
               ;;
       esac
   done

   if [ "$BARE_METAL" = "1" ]; then
      true
   elif [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
      true
   elif [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
      true
   else
      error "${red}${bold}You must choose --bare-metal, --virtualbox or --qcow2.${reset}"
   fi

   source "$MYDIR"/variables
}

do_unchroot() {
   trap "error_handler_unchroot-img" ERR INT TERM

   sync || true

   if [ "$BARE_METAL" = "1" ]; then
      true
   else
      #umount "$CHROOT_FOLDER"/dev/pts || true
      umount "$CHROOT_FOLDER"/dev || true
      umount "$CHROOT_FOLDER"/proc || true
      #umount "$CHROOT_FOLDER"/sys || true
   fi

   umount "$CHROOT_FOLDER/$DEB_INSTALL_FOLDER" || true

   ## Also possibly unmount .backup file for bare metal builds.
   umount "$CHROOT_FOLDER"/etc/resolv.conf || true
   umount "$CHROOT_FOLDER"/etc/hosts || true
   umount "$CHROOT_FOLDER"/etc/hostname || true
   umount "$CHROOT_FOLDER"/etc/network/interfaces || true

   sync || true
}

true "${bold}INFO: Currently running script: $0 ${1+"$@"}${reset}"
parse_cmd_options
do_unchroot
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
